name: CI Build

on:
  push:
    branches:
      - wayland
    paths-ignore:
      - "**.md"
      - "**.markdown"
      - "**.rasi"
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.markdown"
      - "**.rasi"

jobs:
  build-meson-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/meson
        with:
          cc: gcc
  build-meson-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/meson
        with:
          cc: clang
  build-meson-gcc-wayland:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
        with:
          xcb: false
      - uses: ./.github/actions/meson
        with:
          cc: gcc
          xcb: disabled
  build-meson-gcc-xcb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
        with:
          wayland: false
      - uses: ./.github/actions/meson
        with:
          cc: gcc
          wayland: disabled
